"use client";

import Link from "next/link";
import { Drawer } from "@base-ui/react/drawer";
import { Heart, Menu, Sparkles, X } from "lucide-react";

export function MobileNavigation() {
  return <Drawer.Root swipeDirection="right"><Drawer.Trigger aria-label="Open navigation" className="inline-flex size-10 items-center justify-center md:hidden"><Menu className="size-5" /></Drawer.Trigger><Drawer.Portal><Drawer.Backdrop className="fixed inset-0 z-[60] bg-black/60 transition-opacity duration-200 data-ending-style:opacity-0 data-starting-style:opacity-0" /><Drawer.Viewport className="fixed inset-0 z-[60] flex justify-end"><Drawer.Popup className="h-full w-[min(88vw,360px)] bg-obsidian p-6 text-white outline-none transition-transform duration-200 data-ending-style:translate-x-full data-starting-style:translate-x-full"><Drawer.Content><div className="flex items-center justify-between"><Drawer.Title className="font-display text-3xl font-semibold uppercase">Carveo<span className="text-signal">.</span></Drawer.Title><Drawer.Close aria-label="Close navigation" className="inline-flex size-10 items-center justify-center"><X className="size-5" /></Drawer.Close></div><Drawer.Description className="sr-only">Primary navigation</Drawer.Description><nav className="mt-12 grid border-t border-white/15 text-xl"><Drawer.Close render={<Link href="/en-ae/cars" className="border-b border-white/15 py-5">Browse cars</Link>} /><Drawer.Close render={<Link href="/en-ae/market/toyota/land-cruiser" className="border-b border-white/15 py-5">Market insights</Link>} /><Drawer.Close render={<Link href="/en-ae/find" className="flex items-center gap-3 border-b border-white/15 py-5"><Sparkles className="size-5 text-signal" />AI search</Link>} /><Drawer.Close render={<Link href="/en-ae/shortlist" className="flex items-center gap-3 border-b border-white/15 py-5"><Heart className="size-5" />Buyer workspace</Link>} /></nav></Drawer.Content></Drawer.Popup></Drawer.Viewport></Drawer.Portal></Drawer.Root>;
}
