import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import { compareListings, createSession, getListing, getListings, getSavedSearches, saveSearch, sendMessage, type IntentState, type Listing, type ListingPage } from "./api";
import "./styles.css";

const marketPath = "/en-ae";
const formatMoney = (amount: number, currency = "AED") => new Intl.NumberFormat("en-AE", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);
const profileId = (() => { const key = "carveo-profile-id"; const current = localStorage.getItem(key); if (current) return current; const next = crypto.randomUUID(); localStorage.setItem(key, next); return next; })();
const compareKey = "carveo-compare-ids";
const getCompareIds = () => JSON.parse(localStorage.getItem(compareKey) ?? "[]") as string[];

function navigate(path: string) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); }
function age(hours: number) { return hours < 1 ? "Added now" : hours < 24 ? `Added ${hours}h ago` : `Added ${Math.round(hours / 24)}d ago`; }

function Header({ compareCount }: { compareCount: number }) { return <header className="site-header"><button className="logo" onClick={() => navigate(marketPath)} aria-label="Carveo home"><span>c</span>carveo</button><nav><button onClick={() => navigate(`${marketPath}/cars`)}>Browse cars</button><button onClick={() => navigate(`${marketPath}/cars?sort=best_deal`)}>Best deals</button><button onClick={() => navigate(`${marketPath}/cars?body_type=SUV`)}>SUVs</button></nav><button className="compare-link" onClick={() => navigate(`${marketPath}/compare`)}>Compare <b>{compareCount}</b></button></header>; }

function SearchBar({ initial = "", compact = false }: { initial?: string; compact?: boolean }) { const [query, setQuery] = useState(initial); function submit(event: FormEvent) { event.preventDefault(); const params = new URLSearchParams(); if (query.trim()) params.set("query", query.trim()); navigate(`${marketPath}/cars?${params}`); } return <form className={`search-bar ${compact ? "compact" : ""}`} onSubmit={submit}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search make, model, or body type" aria-label="Search cars" /><button>Search</button></form>; }

function ListingCard({ listing, selected, onToggle }: { listing: Listing; selected: boolean; onToggle: (id: string) => void }) { const photo = listing.photos[0]; return <article className="listing-card"><button className="listing-main" onClick={() => navigate(`${marketPath}/cars/${listing.id}`)}>{photo ? <img src={photo} alt={listing.title} /> : <div className="car-placeholder"><span>{listing.make.slice(0, 1)}</span><small>{listing.body_type}</small></div>}<div className="listing-copy"><div className="listing-flags"><span className={`deal-tag ${listing.deal_label.replace(" ", "-").toLowerCase()}`}>{listing.deal_label}</span><span>{listing.source_name}</span></div><h3>{listing.title}</h3><p className="price">{formatMoney(listing.price, listing.currency)}</p>{listing.typical_price && <p className="market-price">Typical market price {formatMoney(listing.typical_price, listing.currency)}{listing.deal_difference && listing.deal_difference > 0 ? ` / ${formatMoney(listing.deal_difference, listing.currency)} below` : ""}</p>}<p className="vehicle-meta">{listing.year} <i /> {listing.mileage_km.toLocaleString()} km <i /> {listing.city}</p><p className="vehicle-meta">{listing.regional_specs ?? "Specs not stated"} <i /> {listing.seller_type} <i /> {age(listing.freshness_hours)}</p></div></button><div className="card-actions"><span>{listing.condition[0]?.claim ?? "Condition not stated"}</span><button className={selected ? "selected" : ""} onClick={() => onToggle(listing.id)}>{selected ? "Added to compare" : "Compare"}</button></div></article>; }

function Home({ compareIds, toggleCompare }: { compareIds: string[]; toggleCompare: (id: string) => void }) { const [featured, setFeatured] = useState<Listing[]>([]); const [recent, setRecent] = useState<Listing[]>([]); useEffect(() => { getListings(new URLSearchParams("sort=best_deal&page_size=3")).then((page) => setFeatured(page.items)); getListings(new URLSearchParams("sort=newest&page_size=4")).then((page) => setRecent(page.items)); }, []); return <><section className="hero"><p className="eyebrow">UAE used cars, made comparable</p><h1>Find the right car at the right market price.</h1><p>Browse UAE inventory, compare similar cars, and see how every asking price sits against the market.</p><SearchBar /><div className="search-suggestions"><button onClick={() => navigate(`${marketPath}/cars?make=Toyota`)}>Toyota</button><button onClick={() => navigate(`${marketPath}/cars?make=Nissan`)}>Nissan</button><button onClick={() => navigate(`${marketPath}/cars?make=Mercedes-Benz`)}>Mercedes-Benz</button><button onClick={() => navigate(`${marketPath}/cars?body_type=SUV`)}>Family SUV</button></div></section><section className="discovery-strip"><div><strong>UAE catalogue</strong><span>10 fixture listings</span></div><div><strong>Typical market price</strong><span>Comparable UAE listings</span></div><div><strong>Source claims only</strong><span>Always verify before buying</span></div></section><SectionHeading title="Best deals right now" text="Listings that sit below their comparable typical market price." link={`${marketPath}/cars?sort=best_deal`} /><div className="card-grid feature-grid">{featured.map((listing) => <ListingCard key={listing.id} listing={listing} selected={compareIds.includes(listing.id)} onToggle={toggleCompare} />)}</div><section className="browse-block"><div><p className="eyebrow">Explore the market</p><h2>Start with what matters.</h2></div><div className="browse-groups"><BrowseGroup label="Make" values={["Toyota", "Nissan", "Mercedes-Benz", "BMW", "Lexus", "Porsche"]} param="make" /><BrowseGroup label="Body type" values={["SUV", "Sedan"]} param="body_type" /><BrowseGroup label="Budget" values={["Under AED 150k", "AED 150k - 220k", "AED 220k+"]} param="budget" /></div></section><SectionHeading title="Recently added" text="Fresh inventory from sources that are configured for the UAE catalogue." link={`${marketPath}/cars?sort=newest`} /><div className="card-grid recent-grid">{recent.map((listing) => <ListingCard key={listing.id} listing={listing} selected={compareIds.includes(listing.id)} onToggle={toggleCompare} />)}</div><section className="trust-note"><span>01</span><div><h2>Carveo compares the market. The seller remains the source.</h2><p>Prices and availability come from listing sources. Deal labels compare asking prices with similar active catalogue listings; they are not inspections or guarantees.</p></div></section></>; }

function BrowseGroup({ label, values, param }: { label: string; values: string[]; param: string }) { const budgetValues: Record<string, string> = { "Under AED 150k": "150000", "AED 150k - 220k": "220000", "AED 220k+": "" }; return <div><h3>{label}</h3>{values.map((value) => <button key={value} onClick={() => { const next = new URLSearchParams(); if (param === "budget" && budgetValues[value]) next.set("price_max", budgetValues[value]); else if (param !== "budget") next.set(param, value); navigate(`${marketPath}/cars?${next}`); }}>{value}</button>)}</div>; }
function SectionHeading({ title, text, link }: { title: string; text: string; link: string }) { return <div className="section-heading"><div><h2>{title}</h2><p>{text}</p></div><button className="text-button" onClick={() => navigate(link)}>View all</button></div>; }

function Browse({ compareIds, toggleCompare }: { compareIds: string[]; toggleCompare: (id: string) => void }) { const [page, setPage] = useState<ListingPage>(); const [error, setError] = useState(""); const [chatText, setChatText] = useState(""); const search = new URLSearchParams(window.location.search); const params = useMemo(() => new URLSearchParams(search), [window.location.search]); const [sessionId, setSessionId] = useState<string>();
  useEffect(() => { getListings(params).then(setPage).catch(() => setError("Could not load the UAE catalogue.")); createSession().then((session) => setSessionId(session.session_id)).catch(() => undefined); }, [params.toString()]);
  const updateParam = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); navigate(`${marketPath}/cars?${next}`); };
  async function refine(event: FormEvent) { event.preventDefault(); if (!sessionId || !chatText.trim()) return; const response = await sendMessage(sessionId, chatText); const intent: IntentState["intent"] = response.intent_state.intent; const next = new URLSearchParams(params); if (intent.make) next.set("make", intent.make); if (intent.models[0]) next.set("model", intent.models[0]); if (intent.budget_max) next.set("price_max", String(intent.budget_max)); if (intent.mileage_max_km) next.set("mileage_max_km", String(intent.mileage_max_km)); if (intent.specifications[0]) next.set("specs", intent.specifications[0]); navigate(`${marketPath}/cars?${next}`); }
  const saveCurrent = async () => { await saveSearch({ profile_id: profileId, name: params.get("query") || params.get("make") || "UAE car search", query: Object.fromEntries(params), priority_refresh: true }); };
  return <section className="browse-page"><div className="browse-intro"><p className="eyebrow">UAE catalogue</p><h1>Browse used cars</h1><p>Compare prices against similar active listings before opening the original ad.</p><SearchBar initial={params.get("query") ?? ""} compact /></div><div className="catalogue-layout"><aside className="filters"><div className="filter-title"><h2>Filters</h2><button onClick={() => navigate(`${marketPath}/cars`)}>Reset</button></div><FilterSelect label="Make" value={params.get("make") ?? ""} options={page?.available_filters.makes ?? []} onChange={(value) => updateParam("make", value)} /><FilterSelect label="Body type" value={params.get("body_type") ?? ""} options={page?.available_filters.body_types ?? []} onChange={(value) => updateParam("body_type", value)} /><FilterSelect label="Specs" value={params.get("specs") ?? ""} options={page?.available_filters.specs ?? []} onChange={(value) => updateParam("specs", value)} /><label>Maximum price<input type="number" placeholder="AED" value={params.get("price_max") ?? ""} onChange={(event) => updateParam("price_max", event.target.value)} /></label><label>Maximum mileage<input type="number" placeholder="km" value={params.get("mileage_max_km") ?? ""} onChange={(event) => updateParam("mileage_max_km", event.target.value)} /></label><form className="chat-refine" onSubmit={refine}><label>Describe what you need</label><textarea value={chatText} onChange={(event) => setChatText(event.target.value)} placeholder="2023 GCC-spec SUV under AED 180k" /><button disabled={!sessionId}>Apply details</button></form></aside><div className="catalogue"><div className="catalogue-toolbar"><p>{page ? `${page.total} UAE cars` : "Loading cars"}</p><div><button onClick={saveCurrent}>Save search</button><label>Sort<select value={params.get("sort") ?? "best_deal"} onChange={(event) => updateParam("sort", event.target.value)}><option value="best_deal">Best deal</option><option value="price_low">Lowest price</option><option value="mileage_low">Lowest mileage</option><option value="newest">Newest</option></select></label></div></div>{error && <p className="error">{error}</p>}<div className="listing-grid">{page?.items.map((listing) => <ListingCard key={listing.id} listing={listing} selected={compareIds.includes(listing.id)} onToggle={toggleCompare} />)}</div>{page && page.total === 0 && <div className="empty-list">No cars match those filters. Try widening the search.</div>}</div></div></section>; }
function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Any</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }

function Detail({ id, compareIds, toggleCompare }: { id: string; compareIds: string[]; toggleCompare: (id: string) => void }) { const [listing, setListing] = useState<Listing>(); useEffect(() => { getListing(id).then(setListing); }, [id]); if (!listing) return <div className="loading-page">Loading listing...</div>; const selected = compareIds.includes(id); return <section className="detail-page"><button className="back-button" onClick={() => navigate(`${marketPath}/cars`)}>Back to results</button><div className="detail-layout"><div className="detail-image"><div className="car-placeholder large"><span>{listing.make.slice(0, 1)}</span><small>{listing.body_type}</small></div></div><div className="detail-overview"><div className="listing-flags"><span className={`deal-tag ${listing.deal_label.replace(" ", "-").toLowerCase()}`}>{listing.deal_label}</span><span>{listing.source_name} / {listing.city}</span></div><h1>{listing.title}</h1><p className="detail-price">{formatMoney(listing.price, listing.currency)}</p><p className="market-price">Typical market price {listing.typical_price ? formatMoney(listing.typical_price) : "not available"}</p><div className="detail-facts"><span>{listing.year}</span><span>{listing.mileage_km.toLocaleString()} km</span><span>{listing.regional_specs ?? "Specs not stated"}</span><span>{listing.seller_type}</span></div><div className="detail-actions"><button onClick={() => toggleCompare(id)}>{selected ? "Remove from compare" : "Add to compare"}</button><a href={listing.source_url} target="_blank" rel="noreferrer">Open original listing</a></div></div></div><div className="detail-sections"><section><h2>Why this price</h2><p>This asking price is compared with active {listing.make} {listing.model} listings of a similar year and regional specification in the UAE catalogue.</p><div className="price-callout"><span>Asking price</span><strong>{formatMoney(listing.price)}</strong><span>Typical price</span><strong>{listing.typical_price ? formatMoney(listing.typical_price) : "Not enough data"}</strong></div></section><section><h2>Listing condition</h2>{listing.condition.map((item) => <div className="evidence" key={item.claim}><strong>{item.claim}</strong><span>{item.evidence ?? "No supporting description was captured."}</span><small>Source confidence {Math.round(item.confidence * 100)}%</small></div>)}</section><section><h2>Features stated by source</h2><div className="feature-list">{listing.features.map((feature) => <span key={feature}>{feature}</span>)}</div><p className="source-disclaimer">Carveo summarizes source-provided claims only. Arrange an independent inspection before committing to a purchase.</p></section></div></section>; }

function Compare({ compareIds, toggleCompare }: { compareIds: string[]; toggleCompare: (id: string) => void }) { const [listings, setListings] = useState<Listing[]>([]); useEffect(() => { if (compareIds.length >= 2) compareListings(compareIds).then((response) => setListings(response.listings)); else setListings([]); }, [compareIds.join(",")]); return <section className="compare-page"><p className="eyebrow">UAE comparison</p><h1>Compare shortlisted cars</h1>{compareIds.length < 2 ? <div className="empty-list">Add at least two cars from browse results to compare them side by side.</div> : <div className="compare-table-wrap"><table><thead><tr><th>Car</th><th>Price</th><th>Typical price</th><th>Mileage</th><th>Specs</th><th>Condition</th><th /></tr></thead><tbody>{listings.map((listing) => <tr key={listing.id}><td><button className="car-link" onClick={() => navigate(`${marketPath}/cars/${listing.id}`)}>{listing.title}<span>{listing.year} / {listing.city}</span></button></td><td>{formatMoney(listing.price)}</td><td>{listing.typical_price ? formatMoney(listing.typical_price) : "-"}</td><td>{listing.mileage_km.toLocaleString()} km</td><td>{listing.regional_specs ?? "Not stated"}</td><td>{listing.condition[0]?.claim ?? "Not stated"}</td><td><button className="remove-button" onClick={() => toggleCompare(listing.id)}>Remove</button></td></tr>)}</tbody></table></div>}</section>; }

function App() { const [path, setPath] = useState(window.location.pathname); const [compareIds, setCompareIds] = useState(getCompareIds); useEffect(() => { const handler = () => setPath(window.location.pathname); window.addEventListener("popstate", handler); return () => window.removeEventListener("popstate", handler); }, []); const toggleCompare = (id: string) => setCompareIds((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : current.length < 4 ? [...current, id] : current; localStorage.setItem(compareKey, JSON.stringify(next)); return next; }); let content = <Home compareIds={compareIds} toggleCompare={toggleCompare} />; if (path.endsWith("/cars")) content = <Browse compareIds={compareIds} toggleCompare={toggleCompare} />; else if (path.includes("/cars/")) content = <Detail id={path.split("/").pop() ?? ""} compareIds={compareIds} toggleCompare={toggleCompare} />; else if (path.endsWith("/compare")) content = <Compare compareIds={compareIds} toggleCompare={toggleCompare} />; return <><Header compareCount={compareIds.length} /><main>{content}</main><footer><span>CARVEO / UAE</span><span>Prices and availability belong to the original source.</span></footer></>; }

createRoot(document.getElementById("root")!).render(<App />);
