/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listings */
        get: operations["listings_api_v1_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_listings__listing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{listing_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Related */
        get: operations["related_api_v1_listings__listing_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets */
        get: operations["markets_api_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{make}/{model}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_api_v1_models__make___model__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompareRequest */
        CompareRequest: {
            /** Listingids */
            listingIds: string[];
        };
        /** CompareResponse */
        CompareResponse: {
            /** Items */
            items: components["schemas"]["Listing"][];
            /** Missingids */
            missingIds: string[];
        };
        /** ConditionEvidence */
        ConditionEvidence: {
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "positive" | "warning" | "unknown";
            /** Label */
            label: string;
            /** Sourceclaim */
            sourceClaim?: string | null;
        };
        /** DealPosition */
        DealPosition: {
            /** Differenceamount */
            differenceAmount?: number | null;
            /** Differencepercent */
            differencePercent?: number | null;
            /**
             * Label
             * @enum {string}
             */
            label: "Below typical" | "Near typical" | "Above typical" | "Limited data";
            /** Samplesize */
            sampleSize: number;
            /** Typicalprice */
            typicalPrice?: number | null;
        };
        /** DuplicateOffer */
        DuplicateOffer: {
            /** Price */
            price: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Listing */
        Listing: {
            /**
             * Bodytype
             * @enum {string}
             */
            bodyType: "SUV" | "Sedan" | "Coupe" | "Hatchback" | "Pickup" | "Convertible";
            /**
             * City
             * @enum {string}
             */
            city: "Dubai" | "Abu Dhabi" | "Sharjah" | "Ajman";
            /** Conditionevidence */
            conditionEvidence: components["schemas"]["ConditionEvidence"][];
            /**
             * Currency
             * @constant
             */
            currency: "AED";
            dealPosition?: components["schemas"]["DealPosition"] | null;
            /** Description */
            description: string;
            /** Duplicateoffers */
            duplicateOffers: components["schemas"]["DuplicateOffer"][];
            /** Features */
            features: string[];
            /**
             * Firstseenat
             * Format: date-time
             */
            firstSeenAt: string;
            /** Id */
            id: string;
            /**
             * Lastseenat
             * Format: date-time
             */
            lastSeenAt: string;
            /** Make */
            make: string;
            /**
             * Market
             * @constant
             */
            market: "ae";
            /** Mileagekm */
            mileageKm: number;
            /** Model */
            model: string;
            /** Photos */
            photos: string[];
            /** Price */
            price: number;
            /** Pricehistory */
            priceHistory: components["schemas"]["PriceObservation"][];
            /**
             * Sellertype
             * @enum {string}
             */
            sellerType: "Dealer" | "Private";
            source: components["schemas"]["SourceAttribution"];
            /**
             * Specifications
             * @enum {string}
             */
            specifications: "GCC" | "American" | "European" | "Japanese";
            /** Title */
            title: string;
            /** Trim */
            trim: string;
            /** Year */
            year: number;
        };
        /** ListingPage */
        ListingPage: {
            /** Items */
            items: components["schemas"]["Listing"][];
            /** Page */
            page: number;
            /** Pagecount */
            pageCount: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** Market */
        Market: {
            /**
             * Code
             * @constant
             */
            code: "ae";
            /**
             * Currency
             * @constant
             */
            currency: "AED";
            /**
             * Locale
             * @constant
             */
            locale: "en-ae";
            /**
             * Name
             * @constant
             */
            name: "United Arab Emirates";
        };
        /** ModelInsights */
        ModelInsights: {
            /** Listings */
            listings: components["schemas"]["Listing"][];
            summary: components["schemas"]["ModelMarketSummary"];
        };
        /** ModelMarketSummary */
        ModelMarketSummary: {
            /** Activelistings */
            activeListings: number;
            /**
             * Lastupdatedat
             * Format: date-time
             */
            lastUpdatedAt: string;
            /** Make */
            make: string;
            /** Maxmileage */
            maxMileage: number;
            /** Maxprice */
            maxPrice: number;
            /** Medianprice */
            medianPrice: number;
            /** Minmileage */
            minMileage: number;
            /** Minprice */
            minPrice: number;
            /** Model */
            model: string;
        };
        /** PriceObservation */
        PriceObservation: {
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Price */
            price: number;
        };
        /** SourceAttribution */
        SourceAttribution: {
            /** Listingurl */
            listingUrl: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Fixture" | "Approved";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_api_v1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listings_api_v1_listings_get: {
        parameters: {
            query?: {
                market?: string;
                q?: string;
                make?: string[];
                model?: string[];
                bodyType?: string[];
                yearMin?: number | null;
                yearMax?: number | null;
                priceMin?: number | null;
                priceMax?: number | null;
                mileageMax?: number | null;
                specifications?: string[];
                sellerType?: string[];
                evidence?: string[];
                city?: string[];
                sort?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_listings__listing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_api_v1_listings__listing_id__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markets_api_v1_markets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"][];
                };
            };
        };
    };
    insights_api_v1_models__make___model__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                make: string;
                model: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInsights"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
