import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketCharts } from "@/components/market-charts";
import { VehicleCard } from "@/components/vehicle-card";
import { resolveModelSegment } from "@/app/en-ae/market/data";
import { catalogueRepository } from "@/repositories";

async function resolveSegment(makeSlug: string, modelSlug: string) {
  return resolveModelSegment(makeSlug, modelSlug, catalogueRepository);
}

export async function generateMetadata({ params }: { params: Promise<{ make: string; model: string }> }): Promise<Metadata> { const { make, model } = await params; const segment = await resolveSegment(make, model); return segment ? { title: `${segment.first.make} ${segment.first.model} UAE market`, description: `Fixture price, mileage and active-listing intelligence for the ${segment.first.make} ${segment.first.model} in the UAE.`, alternates: { canonical: `/en-ae/market/${make}/${model}` } } : { title: "Model market not found" }; }

export default async function MarketPage({ params }: { params: Promise<{ make: string; model: string }> }) {
  const { make, model } = await params; const segment = await resolveSegment(make, model); if (!segment) notFound(); const { first, listings, summary } = segment;
  const structured = { "@context": "https://schema.org", "@type": "ItemList", name: `${first.make} ${first.model} UAE fixture listings`, numberOfItems: listings.length, itemListElement: listings.map((listing, index) => ({ "@type": "ListItem", position: index + 1, url: `/en-ae/cars/${listing.id}`, name: listing.title })) };
  return <main className="bg-marble pb-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured) }} /><section className="relative min-h-[520px] overflow-hidden bg-obsidian text-white"><Image src={first.photos[0]} alt={`${first.make} ${first.model}`} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-black/60" /><div className="shell relative flex min-h-[520px] flex-col justify-end py-12"><p className="text-xs font-semibold uppercase text-signal">UAE model intelligence · fixture data</p><h1 className="font-display mt-2 text-6xl font-semibold uppercase leading-none md:text-8xl">{first.make}<br />{first.model}</h1><div className="mt-8 grid max-w-3xl grid-cols-2 gap-px bg-white/20 md:grid-cols-4"><div className="bg-obsidian/90 p-4"><p className="text-xs text-white/60">Price range</p><p className="mt-1 font-semibold">AED {(summary.minPrice / 1000).toFixed(0)}k–{(summary.maxPrice / 1000).toFixed(0)}k</p></div><div className="bg-obsidian/90 p-4"><p className="text-xs text-white/60">Median</p><p className="mt-1 font-semibold">AED {(summary.medianPrice / 1000).toFixed(0)}k</p></div><div className="bg-obsidian/90 p-4"><p className="text-xs text-white/60">Active fixtures</p><p className="mt-1 font-semibold">{summary.activeListings}</p></div><div className="bg-obsidian/90 p-4"><p className="text-xs text-white/60">Mileage range</p><p className="mt-1 font-semibold">{(summary.minMileage / 1000).toFixed(0)}k–{(summary.maxMileage / 1000).toFixed(0)}k km</p></div></div></div></section>
    <nav className="sticky top-16 z-30 border-b border-border bg-white" aria-label="Model intelligence sections"><div className="shell flex overflow-x-auto">{["Overview", "Prices", "Trims", "Listings"].map((tab) => <a key={tab} href={`#${tab.toLowerCase()}`} className="border-r border-border px-5 py-4 text-sm font-semibold hover:bg-marble">{tab}</a>)}</div></nav>
    <section id="overview" className="shell py-14"><div className="mb-8 max-w-2xl"><p className="text-xs font-semibold uppercase text-muted-foreground">Comparable fixture segment</p><h2 className="font-display mt-2 text-4xl font-semibold uppercase">Price and mileage landscape</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Controls update the visible fixture segment only. These figures are descriptive medians, not a valuation or purchase recommendation.</p></div><MarketCharts listings={listings} /></section>
    <section id="trims" className="border-y border-border bg-white py-14"><div className="shell"><h2 className="font-display text-4xl font-semibold uppercase">Trim snapshot</h2><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead><tr className="border-b border-obsidian"><th className="py-3">Trim</th><th>Year</th><th>Price</th><th>Mileage</th><th>Specs</th></tr></thead><tbody>{listings.map((listing) => <tr key={listing.id} className="border-b border-border"><td className="py-4 font-semibold">{listing.trim}</td><td>{listing.year}</td><td>AED {listing.price.toLocaleString("en-AE")}</td><td>{listing.mileageKm.toLocaleString("en-AE")} km</td><td>{listing.specifications}</td></tr>)}</tbody></table></div></div></section>
    <section id="listings" className="shell py-14"><div className="flex items-end justify-between"><h2 className="font-display text-4xl font-semibold uppercase">Matching inventory</h2><Link href={`/en-ae/cars?make=${encodeURIComponent(first.make)}&model=${encodeURIComponent(first.model)}`} className="text-sm font-semibold">Open catalogue</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{listings.map((listing) => <VehicleCard key={listing.id} listing={listing} />)}</div></section>
  </main>;
}
